### ISSUE TITLE
"Cannot use the ascii-faces screen saver with this version of OSX"

### ISSUE THREAD

**Issue by mrzmyr** [tholman/asciiFaceSaver#3]
Getting the error of "Cannot use the ascii-faces screen saver with this version of OSX" in the preview window.

Any idea how to fix that ?

**Comment by tholman** [comment]
Does this happen on both of the releases - https://github.com/tholman/asciiFaceSaver/releases ?

**Comment by mrzmyr** [comment]
0.80 worked for me, but 0.81 (Version 0.81 for OSX.) did not.

**Comment by tholman** [comment]
Right. Must mean that your OSX version is behind (like mine was, at the time) ... just the nature of swift updating a lot, and not being backwards compatible, I'm afraid.

Glad it works though, going to close this ticket.
