### ISSUE TITLE
Yosemite doesn't support screensaver

### ISSUE THREAD

**Issue by venth** [tholman/asciiFaceSaver#4]
Hi,

I've downloaded latest release (Version 0.81 for OSX). Unfortunately, my mac complains and says that this screen server doesn't work with the current system version. Is there any descriptor, I could change to convince the system, that the screensaver is supported? :)

Yosemite: 10.10.2
Xcode:  6.2 (6776)

**Comment by tholman** [comment]
Any luck with this release - https://github.com/tholman/asciiFaceSaver/releases/tag/0.8 ?

**Comment by venth** [comment]
Works ;) Thank you ;)

**Comment by tholman** [comment]
Awesome :) 

Yeah, not sure what the solution is with this... just seems to be the way it is.

**Comment by venth** [comment]
Deterministic chaos? ;)

**Comment by tholman** [comment]
Something like that! Older versions of swift vs newer versions... I'm curious if I'd got an apple licence and packaged it up, whether it would solve this, or not.
